Update postgres_93

diff --git a/postgres_93 b/postgres_93
--- a/postgres_93
+++ b/postgres_93
@@ -22,12 +22,13 @@
 # Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
 # Use is subject to license terms.
 #
-#ident	"@(#)postgres_93	1.1	20/8/2014 SMI"
+#ident  "@(#)postgres_93        1.1     20/8/2014 SMI"
 
 . /lib/svc/share/smf_include.sh
 
-# SMF_FMRI is the name of the target service. This allows multiple instances 
+# SMF_FMRI is the name of the target service. This allows multiple instances
 # to use the same script.
+SMF_FMRI='svc:/application/database/postgresql_93:default'
 
 getproparg() {
         val=`svcprop -p $1 $SMF_FMRI`
@@ -35,40 +36,39 @@ getproparg() {
 }
 
 check_data_dir() {
-	if [ ! -d $PGDATA ]; then
-		echo "Error: postgresql_93/data directory $PGDATA does not exist"
-		exit $SMF_EXIT_ERR_CONFIG
-	fi
+        if [ ! -d $PGDATA ]; then
+                echo "Error: postgresql_93/data directory $PGDATA does not exist"
+                exit $SMF_EXIT_ERR_CONFIG
+        fi
 
-	if [ ! -w $PGDATA ]; then
-		echo "Error: postgresql_93/data directory $PGDATA is not writable by postgres"
-		exit $SMF_EXIT_ERR_CONFIG
-	fi
+        if [ ! -w $PGDATA ]; then
+                echo "Error: postgresql_93/data directory $PGDATA is not writable by postgres"
+                exit $SMF_EXIT_ERR_CONFIG
+        fi
+        if [ "$PGINIT" = "false" ]; then
+                echo "Notice: postgresql_93/data directory $PGDATA is not initialized"
+                echo "        Calling '$PGBIN/initdb -D $PGDATA' to initialize"
+                $PGBIN/initdb -D $PGDATA
+                if [ $? -ne 0 ]; then
+                        echo "Error: initdb failed"
+                        echo "Hint : If database is already initialized set postgresql_93/initialized property to true."
+                        echo "        svccfg -s $SMF_FMRI \"setprop postgresql_93/initialized = boolean: true\""
+                        echo "        svccfg -s $SMF_FMRI refresh"
+                        exit $SMF_EXIT_ERR
+                fi
+                svccfg -s $SMF_FMRI "setprop postgresql_93/initialized = boolean: true"
+                svccfg -s $SMF_FMRI refresh
+        fi
 
-	if [ "$PGINIT" = "false" ]; then
-		echo "Notice: postgresql_93/data directory $PGDATA is not initialized"
-		echo "        Calling '$PGBIN/initdb -D $PGDATA' to initialize"
-		$PGBIN/initdb -D $PGDATA
-		if [ $? -ne 0 ]; then
-			echo "Error: initdb failed"
-			echo "Hint : If database is already initialized set postgresql_93/initialized property to true."
-			echo "        svccfg -s $SMF_FMRI \"setprop postgresql_93/initialized = boolean: true\""
-			echo "        svccfg -s $SMF_FMRI refresh"
-			exit $SMF_EXIT_ERR
-		fi
-		svccfg -s $SMF_FMRI "setprop postgresql_93/initialized = boolean: true"
-		svccfg -s $SMF_FMRI refresh
-	fi
-
-	if [ ! -d $PGDATA/base -o ! -d $PGDATA/global -o ! -f $PGDATA/PG_VERSION ]; then
-		if [ `ls -a $PGDATA | wc -w` -le 2 ]; then
-			echo "Error: postgresql_93/data directory $PGDATA is empty, but it should be initialized"
-			echo "Hint : check your mountpoints"
-		else
-			echo "Error: postgresql_93/data directory $PGDATA is not empty, nor is it a valid PostgreSQL data directory"
-		fi
-		exit $SMF_EXIT_ERR_CONFIG
-	fi
+        if [ ! -d $PGDATA/base -o ! -d $PGDATA/global -o ! -f $PGDATA/PG_VERSION ]; then
+                if [ `ls -a $PGDATA | wc -w` -le 2 ]; then
+                        echo "Error: postgresql_93/data directory $PGDATA is empty, but it should be initialized"
+                        echo "Hint : check your mountpoints"
+                else
+                        echo "Error: postgresql_93/data directory $PGDATA is not empty, nor is it a valid PostgreSQL data directory"
+                fi
+                exit $SMF_EXIT_ERR_CONFIG
+        fi
 }
 
 PGBIN=`getproparg postgresql_93/bin`
@@ -77,8 +77,8 @@ PGLOG=`getproparg postgresql_93/log`
 PGINIT=`getproparg postgresql_93/initialized`
 
 if [ -z $SMF_FMRI ]; then
-	echo "Error: SMF framework variables are not initialized"
-	exit $SMF_EXIT_ERR
+        echo "Error: SMF framework variables are not initialized"
+        exit $SMF_EXIT_ERR
 fi
 
 if [ -z $PGDATA ]; then
@@ -89,21 +89,20 @@ fi
 if [ -z $PGLOG ]; then
         echo "Error: postgresql_93/log property not set"
         exit $SMF_EXIT_ERR_CONFIG
-fi
-
+fi        
 
 case "$1" in
 'start')
-	check_data_dir
-        $PGBIN/pg_ctl -D $PGDATA -l $PGDATA/$PGLOG start
+        check_data_dir
+        su - postgres -c "$PGBIN/pg_ctl -D $PGDATA -l $PGDATA/$PGLOG start"
         ;;
 
 'stop')
-        $PGBIN/pg_ctl -D $PGDATA stop
+        su - postgres -c "$PGBIN/pg_ctl -D $PGDATA stop"
         ;;
 
 'refresh')
-        $PGBIN/pg_ctl -D $PGDATA reload
+        su - postgres -c "$PGBIN/pg_ctl -D $PGDATA reload"
         ;;
 
 *)
